gemoc/ale-lang

docs/index.md

A few mistakes I found in the first page of the website, if you're interested
(I won't do that for all pages of the docs though :) )

[docs/index] Fix typos and small rephrasings

---

plugins/org.eclipse.emf.ecoretools.ale.examples/.classpath
releng/org.eclipse.emf.ecoretools.ale.target-platform.win32/.project
releng/org.eclipse.emf.ecoretools.ale.target-platform.win32/org.eclipse.emf.ecoretools.ale.target-platform.win32.target
releng/org.eclipse.emf.ecoretools.ale.target-platform/.project
releng/org.eclipse.emf.ecoretools.ale.target-platform/.settings/org.eclipse.core.resources.prefs

Existing target platform is tailored for Linux and cannot be used on Windows. A new one is hence introduced in the the `releng/org.eclipse.emf.ecoretools.ale.target-platform.win32` project.
Also introduces small enhancements:
- Remove nonexistent _src/_ folder from ale.examples bundle's classpath
- Make ale.target-platform an Eclipse IDE project

Provide a target platform for Windows

---

Jenkinsfile

This PR adds a jenkinsfile allowing to build ALE in multibranch configuration.
I've also set up a new CI configuration https://ci.inria.fr/gemoc/job/ale-lang/ that looks for changes in the branches.
This contributes to https://github.com/gemoc/ale-lang/issues/63 by building all branches in the repo
The deployment of the artifact to the web site is triggered by adding a tag "release-XXX" to the commit (should be done only on master branch)
note: it is important to clean old unused branches in order to save disk space on the CI server.

Jenkinsfile4ale

---

plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/EvalEnvironment.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/MethodEvaluator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/AstBuilder.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/Dsl.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/DslBuilder.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/visitor/ParseResult.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/BaseValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/NameValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/OpenClassValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/TypeValidator.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/AlePreferenceStore.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/AlePropertyPage.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/launchconfig/AleLaunchConfigurationTab.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/launchconfig/LaunchShortcut.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/launchconfig/RunModelAction.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/services/Services.java
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/WorkbenchDsl.java
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/listener/AleWorkspaceListener.java
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/resource/AleResource.java
plugins/org.eclipse.emf.ecoretools.ale.xtext/src/org/eclipse/emf/ecoretools/validation/AleValidator.xtend
plugins/org.eclipse.emf.ecoretools.ale/src/org/eclipse/emf/ecoretools/ale/ALEInterpreter.java
plugins/org.eclipse.emf.ecoretools.ale/src/org/eclipse/emf/ecoretools/ale/debug/DebugLookupEngine.java
plugins/org.eclipse.emf.ecoretools.ale/src/org/eclipse/emf/ecoretools/ale/debug/ILookupEngineListener.java

Main improvements are:
- remove redundant type specifications by the diamond operator <>
- use static imports when calling Collectors' functions
Also brings some little changes:
- [RunModelAction](https://github.com/gemoc/ale-lang/blob/dc514c8fd46d27b89124dbf43bbcb2424fbbb310/plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/launchconfig/RunModelAction.java#L84): wrap execution of the interpreter in a try-catch statement to ensure `System.out` is always reset to its original value
- [RunModelAction](https://github.com/gemoc/ale-lang/blob/dc514c8fd46d27b89124dbf43bbcb2424fbbb310/plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/launchconfig/RunModelAction.java#L115): (possibly breaking change) cancel the execution …

Improve code quality by following Sonar's advice

---

plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/DiagnosticLogger.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/DynamicFeatureRegistry.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/MethodEvaluator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/AstBuilder.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/BaseValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/IValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/NameValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/OpenClassValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/TypeValidator.java
plugins/org.eclipse.emf.ecoretools.ale.xtext/src/org/eclipse/emf/ecoretools/validation/AleValidator.xtend

This PR fixes a few bugs related to the `+=` and `-=` operators.
The execution is now stopped in the following cases:
- `+=` is called on an object that is not a list, not a string and not an integer
- `-=` is called on an object that is not a list, not a string and not an integer
- `+=` is called on a list and the right operand cannot be added to the list because their types are incompatible
The type checker has also been enhanced and shows errors when:
- `+=` or `-=` is called on an inexisting variable
- `+=` or `-=` is called on `self`
- `+=` is called on a feature and the right operand cannot be added to the feature because their types are incompatible
The type checker still has flaws because it does not check the types of the operands when `+=` is called on a local variable (it would …

Improve the += and -= operators

---

plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/BaseValidator.java
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/assignForbiddenValueToResult.implem
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/resultRead.implem
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/BaseValidatorTest.java
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/NameValidatorTest.java
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/OpenClassValidationTest.java
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/TypeValidatorTest.java
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/ValidationMessages.java

Fix #40.
The type checker was unaware of the `result` variable and was hence providing irrelevant errors when reading it.
Fixed the issue by programmatically adding a `result` variable to the stack when entering a method scope (the exact same thing is already done for `self`). This variable has the same type as the `EOperation` thus allowing the type checker to perform well.
<div align="left">
</div>

Prevent "couldn't find the 'result' variable" error

---

plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/OpenClassValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/QualifiedNames.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/TypeValidator.java
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/openingLocallyDefinedRuntimeClass.implem
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/openingNonExistingClass.implem
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/OpenClassValidationTest.java

Fix #19.
```
behavior helloworld;
open class Foo {
}
```
Here, `Foo` can be:
- a static class defined within an Ecore metamodel,
- a runtime class defined in the same _.ale_ file,
- a runtime class defined in another _.ale_ file.
Otherwise, an error is shown.
```
behavior helloworld;
open class Foo {
}
```
Will raise a warning if a class `Foo` is defined:
- in a package not called `helloworld`,
- in an _.ale_ file which behavior is not `helloworld`

Opening a class that does not exist should raise an error

---

plugins/org.eclipse.emf.ecoretools.ale.ide.ui/META-INF/MANIFEST.MF
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/Activator.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/launchconfig/RunModelAction.java
plugins/org.eclipse.emf.ecoretools.ale.xtext/src/org/eclipse/emf/ecoretools/validation/AleValidator.xtend
plugins/org.eclipse.emf.ecoretools.ale/src/org/eclipse/emf/ecoretools/ale/ALEInterpreter.java
tests/org.eclipse.emf.ecoretools.ale.tests/META-INF/MANIFEST.MF
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/interpreter/test/EvalTest.java
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/lookup/test/LookupTest.java

This PR adds a close() method on ALEInterpreter
This allows to properly dispose the resource retained by the `queryEnvironment` and the `javaExtensions`.
The class extends AutoCloseable, so users of this class may use `try with resource`.
The method eval is protected against the use of closed interpreter by declaring that it can throw a ClosedALEInterpreterExcpetion.  This declaration also helps to know that the close method must be calle after use of the interpreter.
This PR should fix https://github.com/gemoc/ale-lang/issues/54 and contribute to fix memory while using the interpreter in other contexts.

add autoclosable api to ALEInterpreter

---

plugins/org.eclipse.emf.ecoretools.ale/META-INF/MANIFEST.MF
plugins/org.eclipse.emf.ecoretools.ale/plugin.properties
plugins/org.eclipse.emf.ecoretools.ale/src/org/eclipse/emf/ecoretools/ale/ALEDynamicExpressionEvaluator.java
plugins/org.eclipse.emf.ecoretools.ale/src/org/eclipse/emf/ecoretools/ale/Messages.java
plugins/org.eclipse.emf.ecoretools.ale/src/org/eclipse/emf/ecoretools/ale/messages.properties

This class offers services similar to `org.eclipse.sirius.common.acceleo.aql.business.internal.AQLSiriusInterpreter` but without the registration to the workspace listener.
If offers the possibility to parse and evaluate string expressions and return various kinds of objects.
It relies on the queryEnvironment of an existing ALEInterpreter. (ie. this is the responsibility of this ALEInterpreter to clean/dispose the query environment when not use anymore)

add ALEDynamicExpressionEvaluator

---

plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/MethodEvaluator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/services/DynamicEObjectFeatureAccess.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/services/EvalBodyService.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/services/ServiceCallListener.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/visitor/ModelBuilder.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/BaseValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/impl/ConvertType.java
tests/org.eclipse.emf.ecoretools.ale.tests/input/eval/initLocalVariables.implem
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/callMethodTakingSequence.implem
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/forEachIntRange.implem
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/forEachSequence.implem
tests/org.eclipse.emf.ecoretools.ale.tests/model/Mix.xmi
tests/org.eclipse.emf.ecoretools.ale.tests/model/attributesOfDifferentTypes.ecore
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/interpreter/test/EvalTest.java
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/TypeValidatorTest.java

Improve management of `Sequence` instances by fixing the following bugs:
- #3 — Sequence cannot be used in operations
- #10 — Sequences cannot be used in _for each_ loops
- #20 — Methods taking parameters of type Sequence cannot be called
- #42 — Empty Sequence cannot be declared
- #56 — Local variables cannot be declared without an initial value
- #75 — Attributes of type Sequence cannot be initialized
Basically, the following code is now legal:
```ale
open class EClass {
0..* String stringNumbers := Sequence{'1', '2', '3'};
@main
def void main(){
Sequence(Integer) numbers := self.asInt(self.stringNumbers);
}
def Sequence(Integer) asInt(Sequence(String) numbers) {
result := numbers->collect(number | number.toInteger());
}
}
```
This PR contributes to #74 by taking the following approach: …

Enhance support for sequences

---

plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/AleUiModule.xtend
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/contentassist/AleProposalProvider.xtend
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/contentassist/AleTemplateProposal.xtend
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/contentassist/AleTemplateProposalProvider.xtend
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/contentassist/TypeUtils.xtend

Because current autocompletion is not helpful (fix #92).
`AleProposalProvider` has been enhanced to dynamically retrieve `self`'s attributes from both the Ecore model and the ALE script.
A new `AleTemplateProposalProvider` has been created to dynamically retrieve `self`'s operations from both the Ecore model and the ALE script. These operations are autocompleted as [templates](https://www.eclipse.org/pdt/help/html/templates.htm). The reason why I chose to use templates for operations instead of bare proposals is because a template is defined by a pattern that can contain one or several placeholders; once the template is inserted in the editor these placeholders can easily be edited by the user. I rely on this feature to make easier for the user to set the parameters of an operation.
With …

[Editor] Autocomplete attributes and methods of "self"

---

plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/contentassist/AleProposalProvider.xtend
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/contentassist/AleTemplateProposalProvider.xtend

Because last commit 7fb08bf broke the CI due to Xtend 2.19 being used and we're not ready yet to migrate from 2.14 (see #99)

[CI] Make Xtend code compliant with Xtend 2.14

---

plugins/org.eclipse.emf.ecoretools.ale.xtext.ide.theme/.classpath
plugins/org.eclipse.emf.ecoretools.ale.xtext.ide.theme/.project
plugins/org.eclipse.emf.ecoretools.ale.xtext.ide.theme/.settings/org.eclipse.jdt.core.prefs
plugins/org.eclipse.emf.ecoretools.ale.xtext.ide.theme/META-INF/MANIFEST.MF
plugins/org.eclipse.emf.ecoretools.ale.xtext.ide.theme/build.properties
plugins/org.eclipse.emf.ecoretools.ale.xtext.ide.theme/css/dark-theme.css
plugins/org.eclipse.emf.ecoretools.ale.xtext.ide.theme/plugin.xml
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/AleHighlightingConfiguration.xtend
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/AleSemanticHighlightingCalculator.xtend
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/AleUiModule.xtend

Closes #93, closes #94.
Beautifies ALE's editor in dark theme:
<div align="center">
</div>
The dark theme is similar to JDT's one. I tested on both Eclipse Photon (ALE's current target platform) and 2019-12 (latest release at the time of writing).
- the new 'org.eclipse.emf.ecoretools.ale.xtext.ide.theme' bundle provides the colors to use in dark theme as CSS
- new classes have been created in the xtext.ui bundle to identify the tokens semantically so that they can be colored properly
- the symbolic name of the `xtext.ide.theme` bundle is currently `org.eclipse.emf.ecoretools.Ale`. This is because we need a bundle named after Xtext language so that Eclipse's CSS Engine properly override color preferences when switching to dark theme in Photon
- see [this …

[Editor] Enhance dark theme

---

plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/TypeValidator.java
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/AleSemanticHighlightingCalculator.xtend
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/forEachRangeFromMethodCall.implem
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/TypeValidatorTest.java

Closes #102
Correctly type checks:
```ale
def void main() {
for (city in self.cities()) {
city.log();
}
}
def Sequence(String) cities() {
result := Sequence{'Paris', 'London'};
}

[Type Checker] Allow use of methods to define for-each loops' range

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/ITypeChecker.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/IValidationMessageFactory.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/TypeValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/impl/TypeChecker.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/impl/ValidationMessageFactory.java
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/assignNullToAttribute.implem
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/assignNullToLocalVariables.implem
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/initializeAttributesToNull.implem
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/NameValidatorTest.java
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/TypeValidatorTest.java

Close #64.
EDIT: allows to assign `null` to *any variable*. At first I wanted to prevent `null` assignment for primitives (numbers, booleans and even strings) but I believe that may have arm compatibility with Java services that may return `null` instead of a Boolean, an Integer or a String.
- the code has been slightly simplified: `TypeValidator` now valides attribute initializations in the same way it validates other assignments
- as a result, when assigning an illegal value to an attribute the editor now underlines the illegal value only instead of the whole expression

Allow to assign null

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/META-INF/MANIFEST.MF
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/plugin.xml
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/launchconfig/UiUtils.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/project/WorkspaceAleProject.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/wizards/NewAleProjectConfigurationWizardPage.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/wizards/NewAleProjectWizard.java
plugins/org.eclipse.emf.ecoretools.ale.ide/META-INF/MANIFEST.MF
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/project/AleProject.java
tests/org.eclipse.emf.ecoretools.ale.ide.ui.tests/META-INF/MANIFEST.MF
tests/org.eclipse.emf.ecoretools.ale.ide.ui.tests/src/org/eclipse/emf/ecoretools/ale/ide/helloworld/tests/WorkspaceAleProjectTest.java
tests/org.eclipse.emf.ecoretools.ale.ide.ui.tests/src/org/eclipse/emf/ecoretools/ale/ide/helloworld/tests/commons/NewAleProjectWizardBot.java

Should close #98.
Provide a wizard that allows to create an ALE project with:
- either an existing or a new Ecore model
- a `.ale` file containing only `behavior <name>;`
- a `.dsl` file linking the .ecore and the .ale files
- (optional) a Sirius representation of the Ecore model
- (optional) the Java nature

Provide a 'New ALE Project' wizard

---

plugins/org.eclipse.emf.ecoretools.ale.core/META-INF/MANIFEST.MF
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/DiagnosticLogger.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/MethodEvaluator.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/META-INF/MANIFEST.MF
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/plugin.xml
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/io/AleConsole.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/io/HyperlinkAleConsoleMatcherListener.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/launchconfig/AleEvaluationJob.java

Close #110.
- the title of the console changes as the execution progresses
- error messages are shorter and printed in a red font
- stacktraces are cleaner and provide hyperlinks to source code
Given the following code (`self.piou` does not exist):
```kotlin
behavior piou;
open class Piou {
@main
def void main() {
self.foo();
}
def void foo() {
self.piou.foo();		
}
}
```
The console was printing the following message:
<details>
<summary><i>Click to expand</i></summary>
```kotlin
aqlFeatureAccess(org.eclipse.emf.ecore.EObject,java.lang.String) with arguments [org.eclipse.emf.ecore.impl.DynamicEObjectImpl@5c48f04e (eClass: org.eclipse.emf.ecore.impl.EClassImpl@2e83f3f5 (name: Piou) (instanceClassName: null) (abstract: false, interface: false)), piou] failed:
Feature piou not found in EClass …
```

Improve ALE console with a clean, colored stacktrace with hyperlink

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/visitor/ModelBuilder.java
tests/org.eclipse.emf.ecoretools.ale.tests/input/eval/doubleAsParameter.implem
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/interpreter/test/EvalTest.java

Closes #36.
Methods taking `Double` as parameters were not found by the interpreter.
The `ModelBuilder` was turning `Double` types into `UnresolvedEClassifier` types because `Double` with an uppercase `D` has been forgotten here:
https://github.com/gemoc/ale-lang/blob/2c1f7145d8eae49a7b06ce4d61c33f68167ba231/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/visitor/ModelBuilder.java#L535-L546
`Real` and `ecore::EDouble` are not concerned by this limitation because we use another method (`toEMF`) to turn them into EMF types:
https://github.com/gemoc/ale-lang/blob/2c1f7145d8eae49a7b06ce4d61c33f68167ba231/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/visitor/ModelBuilder.java#L551-L561
TBH I don't know …

[Parser] Properly handle "Double" types (fix #36)

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/MethodEvaluator.java
tests/org.eclipse.emf.ecoretools.ale.tests/input/eval/addAllCollectionWithOperator.implem
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/interpreter/test/EvalTest.java

Closes #120.
Allows to use the `+=` operator on local variables and static attributes (declared in Ecore) when both operands are collections.
Helped to identify issue #128 (no runtime error when the collections hold incompatible types).

Allow the '+=' operator to concatenate collections

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/DynamicFeatureRegistry.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/visitor/ModelBuilder.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/BaseValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/IConvertType.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/IValidationMessageFactory.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/NameValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/impl/ConvertType.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/impl/ValidationMessageFactory.java
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/assignVoid.implem
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/interpreter/test/EvalTest.java
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/parser/test/BuildTest.java
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/NameValidatorTest.java
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/TypeValidatorTest.java

Little refactor of the parser (`ModelBuilder`) to create a cleaner EMF model.
As of now, AQL collections are turned into EDataType instances holding an EEList type and with bounds [0, 1]. This commit turns collections into ETypedElement holding the actual type with relevant bounds instead.
This homogenize datatypes and should ease further developments, e.g. to handle Sets properly (#67).
Also provides a little enhancement: using `+=` or `-=` on the `result` variable within a void operation now leads to the following error: _'result' is not available in a void method. Change method's return type_.
The error was already shown when using the `:=` operator.

Properly turn AQL declarations into EMF objects

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/DslBuilder.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/preferences/AleProjectPreferences.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/preferences/AleEnvironmentPropertyPage.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/services/Services.java
plugins/org.eclipse.emf.ecoretools.ale.ide/META-INF/MANIFEST.MF
plugins/org.eclipse.emf.ecoretools.ale.ide/plugin.xml
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/Activator.java
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/project/AleProject.java
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/project/impl/AleAware.java
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/refactoring/RenamePathsInDslFilesChange.java
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/refactoring/RenamePathsInProjectPreferencesChange.java
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/refactoring/RenamePathsToAleResources.java

Closes #70.
- paths in both _.dsl_ files and project preferences are updated when:
- the enclosing project is renamed
- a folder containing an ALE resource (source file / metamodel) is renamed
- undo operation is supported
<details>
<summary><i>Click to show</i></summary>
<br/>
</details>
I also wanted to implement a preview of the changes (in a textual diff) but I found no code to reuse and that would thus have costed too much time. The steps are:
1. Contribute to the `org.eclipse.ltk.ui.refactoring.changePreviewViewers` extension point
2. Provide a class implementing `org.eclipse.ltk.ui.refactoring.IChangePreviewViewer`
- AleAware.getEnvironment() does not return a `Normalized` instance anymore. `Normalized` was turning each source file URI into an absolute file path, making code in …

[IDE] Update paths to resources when a container is renamed

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/AstBuilder.java
tests/org.eclipse.emf.ecoretools.ale.tests/input/validation/assignmentsInvolvingRuntimeClasses.implem
tests/org.eclipse.emf.ecoretools.ale.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/TypeValidatorTest.java

Closes #51
Make sure that the `EPackage` containing the dynamic classes is actually taken into account by forcing the environment to remove the previously registered `EPackage`.
```kotlin
behavior helloworld;
open class EClass {
helloworld::MyClass attribute;
@main
def void main() {
helloworld::MyClass aMyClass;
aMyClass := helloworld::MyClass.create();
ecore::EClass helloworld := aMyClass.refEClass;
aMyClass := self.attribute;	
aMyClass := self;	  // shows an error
}
}
class MyClass {
EClass refEClass;
}
```

[Type Checker] Handle dynamic classes

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/services/Services.java

Closes #39
- when an ALE project contains a Sirius representation, this representation can show
both static and dynamic data, even if the metamodel(s) and the source file(s) are
in other projects
- the project is retrieved from the location of the .aird file
- the ALE environment is loaded from this project and used to fed the Behavior layer
The capture below show a workspace with two project:
- `minifsm` defines a FSM metamodel
- `minifsm-execution` defines a semantics for this FSM
The Sirius representation defined by `minifsm-execution` can show the semantics defined in the `minifsm-execution`:
> *Note*: don't mind the red crosses, it looks like some icons are missing in my environment

[Sirius] Enhance the 'Behavior' layer to handle split projects

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/internal/AntlrAstToAleBehaviorsFactory.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/BaseValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/NameValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/OpenClassValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/SafeValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/TypeValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/impl/AstLookup.java
plugins/org.eclipse.emf.ecoretools.ale.xtext/META-INF/MANIFEST.MF
plugins/org.eclipse.emf.ecoretools.ale.xtext/src/org/eclipse/emf/ecoretools/AleXtextPlugin.java
plugins/org.eclipse.emf.ecoretools.ale.xtext/src/org/eclipse/emf/ecoretools/validation/AleValidator.xtend
tests/org.eclipse.emf.ecoretools.ale.core.tests/input/validation/openingEnum.implem
tests/org.eclipse.emf.ecoretools.ale.core.tests/model/test.ecore
tests/org.eclipse.emf.ecoretools.ale.core.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/OpenClassValidationTest.java

Fix #149.
The CI pass and everything looks good to me. I'll make a last check on GEMOC Studio then proceed to merge the PR.
- validators are now decorated with `SafeValidator` which ensures that exceptions thrown by validation methods are caught, logged then discard to continue the validation
- the case where `ExtendedClass::getBaseClass` returns has been handled and shouldn't cause errors anymore
- if an internal error still occurs during validation but outside validators then `AleValidator` will catch it and log it

Make Xtext validators resilient

---

CHANGELOG.md
examples/logo.example/data/LogoProgram.dsl
examples/logo.example/data/logo.dsl
examples/logo.standalone/logo-standalone.dsl
examples/minifsm/model/MiniFsm.dsl
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/env/impl/FileBasedAleEnvironment.java
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/listener/AleSessionManagerListener.java

Close #26.
Use the `ecore` and `ale` keys in *.dsl* because they are the keys understood by the GEMOC Studio:
*fsm.dsl*
```properties
ecore=platform\:/resource/fsm/model/fsm.ecore
ale=platform\:/resource/fsm/src-ale/fsm.ale
```
By the way @dvojtise, do we really want to use `ale` as a key? If I remember well we had a discussion with other members of the team and kind of agreed for `org.eclipse.emf.ecoretools.ale.interpreter` instead. Am I right? I so, should I make the change right now or postpone it and merge the PR anyway?

[IDE] Use "ecore" and "ale" keys instead of "syntax" and "semantics" in .dsl

---

plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/notapi/DynamicFeatureRegistry.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/BaseValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/validation/AleEditorMessages.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/validation/EditorMarkerFormatter.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/validation/ale_editor_messages.properties
plugins/org.eclipse.emf.ecoretools.ale.xtext/src/org/eclipse/emf/ecoretools/validation/AleValidator.xtend

Also related to #149.
- a class might not have a base class (e.g. when attempting to open a EEnum)
- `DynamicFeatureRegistry` takes this case into account
- `BaseValidator` properly reports internal errors instead of printing them to the console
- `AleValidator` logs internal errors to ease debug
- `EditorMarkerFormatter` shows internal error markers on the editor to spotlight them

[Interpreter] Prevent internal errors when looking up attribute of a class without a base class

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.core/model/Implementation.ecore
plugins/org.eclipse.emf.ecoretools.ale.core/model/Implementation.genmodel
plugins/org.eclipse.emf.ecoretools.ale.core/src-gen/org/eclipse/emf/ecoretools/ale/implementation/ImplementationPackage.java
plugins/org.eclipse.emf.ecoretools.ale.core/src-gen/org/eclipse/emf/ecoretools/ale/implementation/impl/ImplementationFactoryImpl.java
plugins/org.eclipse.emf.ecoretools.ale.core/src-gen/org/eclipse/emf/ecoretools/ale/implementation/impl/ImplementationPackageImpl.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/internal/ExtensionEnvironment.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/internal/MethodEvaluator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/internal/AntlrAstToAleBehaviorsFactory.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/internal/AntlrAstToBehaviorsAstAdapter.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/BaseValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/NameValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/TypeValidator.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/impl/AstLookup.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/impl/ConvertType.java
tests/org.eclipse.emf.ecoretools.ale.core.tests/src/org/eclipse/emf/ecoretools/ale/core/parser/BuildTest.java
tests/org.eclipse.emf.ecoretools.ale.core.tests/src/org/eclipse/emf/ecoretools/ale/core/validation/test/NameValidatorTest.java

Closes #119 
Closes #165 
Make sure Acceleo errors are shown as markers & prevent errors when overridding method from a parent class.

Handle overridden methods & show AQL errors as markers

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.core/META-INF/MANIFEST.MF
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/impl/AleInterpreter.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/internal/impl/AleEnvironmentClassLoading.java

Close #151 
Get rid of AQL's habit to fetch every EPackage it finds in dependencies and to add it to the environment.
- `AleEnvironmentClassLoading` is a class loading that finds Java services declared in the current project but does not fetch any EPackage

[Interpreter|Validators] Add only relevant EPackages to the environment

---

CHANGELOG.md
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/AleUiModule.xtend
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/hover/AleDispatchingEObjectHover.java
plugins/org.eclipse.emf.ecoretools.ale.xtext.ui/src/org/eclipse/emf/ecoretools/ui/hover/AleHoverProvider.java

Add tooltips to the editor.
- hovering the `open` and `behavior` keywords show tooltips about their meaning
- hovering the ID after `behavior` shows available EPackages
- hovering the name of an open class shows the fully qualified name of this class and where it comes from
_Hover on open class:_
_Hover on behavior:_

[Editor] Add tooltips when open class/behavior are hovered

---

plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/env/impl/FileBasedAleEnvironment.java
plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/IOUtils.java
plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/project/WorkspaceAleProject.java
plugins/org.eclipse.emf.ecoretools.ale.ide/src/org/eclipse/emf/ecoretools/ale/ide/env/WithAbsoluteBehaviorPathsAleEnvironment.java

Closes https://github.com/gemoc/ale-lang/issues/158 and https://github.com/gemoc/ale-lang/issues/188
- make sure to use system path (instead of workspace relative path) when creating `file:/` uri
- fix uri saved in the .dsl file when creating project (the uri was of the form : `platform:/resource/platform:/resource/project...`)
- avoid the `/:` in the value parts of the .dsl file
This PR also removes some duplicated code between IOUtils and WithAbsoluteBehaviorPathsAleEnvironment

Fix project creation on linux

---

plugins/org.eclipse.emf.ecoretools.ale.ide.ui/plugin.xml

AleInvocationDelegateFactory was moved/renamed in
https://github.com/gemoc/ale-lang/pull/136 this PR adapt the plugin.xml to it
(note, Actually I don't really know what is its purpose, I only fixed it to point to an existing file)

fix path to AleInvocationDelegateFactory in plugin.xml
